# Testcase: changesets_symlinked_entries.tar
#
# To Build:
#   docker build -f Dockerfile.changesets_symlinked_entries . -t changesets_symlinked_entries:latest
#
# To Export:
#   docker save changesets_symlinked_entries:latest > changesets_symlinked_entries.tar
#
# To Run:
#   docker run -it changesets_symlinked_entries:latest /bin/sh
#
# To Push:
#   docker tag changesets_symlinked_entries:latest fossaeng/changesets_symlinked_entries:latest
#   docker push fossaeng/changesets_symlinked_entries:latest
FROM busybox

RUN echo 'a' > filea.txt
WORKDIR /tmp

RUN echo 'b' > fileb.txt
WORKDIR /app

RUN echo 'c' > filec.txt
WORKDIR /tmp
